package dev.myclinic.scala.model

enum Shuukeisaki(val code: String):
  case SHOSHIN extends Shuukeisaki("110")
  case SAISHIN_SAISHIN extends Shuukeisaki("120")
  case SAISHIN_GAIRAIKANRI extends Shuukeisaki("122")
  case SAISHIN_JIKANGAI extends Shuukeisaki("123")
  case SAISHIN_KYUUJITSU extends Shuukeisaki("124")
  case SAISHIN_SHINYA extends Shuukeisaki("125")
  case SHIDOU extends Shuukeisaki("130")
  case ZAITAKU extends Shuukeisaki("140")
  case TOUYAKU_NAIFUKUTONPUKUCHOUZAI extends Shuukeisaki("210")
  case TOUYAKU_GAIYOUCHOUZAI extends Shuukeisaki("230")
  case TOUYAKU_SHOHOU extends Shuukeisaki("250")
  case TOUYAKU_MADOKU extends Shuukeisaki("260")
  case TOUYAKU_CHOUKI extends Shuukeisaki("270")
  case CHUUSHA_SEIBUTSUETC extends Shuukeisaki("300")
  case CHUUSHA_HIKA extends Shuukeisaki("311")
  case CHUUSHA_JOUMYAKU extends Shuukeisaki("321")
  case CHUUSHA_OTHERS extends Shuukeisaki("331")
  case SHOCHI extends Shuukeisaki("400")
  case SHUJUTSU_SHUJUTSU extends Shuukeisaki("500")
  case SHUJUTSU_YUKETSU extends Shuukeisaki("502")
  case MASUI extends Shuukeisaki("540")
  case KENSA extends Shuukeisaki("600")
  case GAZOUSHINDAN extends Shuukeisaki("700")
  case OTHERS extends Shuukeisaki("800")
